---
title: "Homework 7"
author: "Lingyun Guo"
date: "3/15/2020"
output:
  pdf_document: default
  html_document: default
---

\newcommand\prob{\mathbb{P}}
\newcommand\E{\mathbb{E}}
\newcommand\ar{\phi}
\newcommand\ma{\psi}
\newcommand\var{\mathrm{Var}}
\newcommand\cov{\mathrm{Cov}}

---

### Question 7.1. 

Two midterm projects that I selected:

 - Seasonal sugar? A study of monthly sugar production in U.S. from 1972 to 2020
 - Weekly Butter Prices from 2012 to 2017

I selected these two projects because they both analyzed a time series related to the food industry like I did. I think it is more sensible to compare my project from them and learn from them.

For the "sugar" project, I think it has a better organization than mine, and its citation was also well-organized. In addition, it included QQplots in the analysis part and an additional prediction part, which served as a validation for its analysis. For the "butter" project, I think the introduction part and data cleaning and exploration parts wrote very well. When I was writing my part, I didn't know how to properly approach the topic or explain what I had done. This project clearly explained the background of the dataset and the data cleaning process, which made a lot of sense.

### Question 7.2

I find reading the project list really helpful, as it helped me learn a lot of new words (foreign traditions, diseases) that I' have've never heard of. I selected the project *1928-1931 Detroit Mumps Infection Analysis* because under current situation, I also want to analyze a epidemic and this would be a good reference. This project firs includes explorations and before diving into the anaysis, it built a diagram to describe its architecture, which is clear and straight forward. I think it is much better than direct presenting codes and plots. Also I am attracted by the fancy plots in sections 4 and 5, which I hope to learn in the upcoming lectures.

### Question 7.3

Dataset: *SARS 2003 Outbreak Complete Dataset*. https://www.kaggle.com/imdevskp/sars-outbreak-2003-complete-dataset.

As I previously mentioned, I want to analyze the complete process of an epidemic and practice the SIR or SEIR models. It is natural to think of COVID-19, and Kaggle provides a bunch of dataset related to it. But this is an ongoing process and cannot be considered "finished". On the other hand, SARS was a previously appeared virus of similarity and is often compared to COVID-19 virus these days. Therefore, I think it is of significance to analyze the growth and cease of SARS, since we may find inspiring points from the results.

### Question 7.4

1. W20 Midterm project 1, *Seasonal sugar? A study of monthly sugar production in U.S. from 1972 to 2020*. https://ionides.github.io/531w20/midterm_project/project1/Midterm-Project.html.
2. W20 Midterm project 2, *Weekly Butter Prices from 2012 to 2017*. https://ionides.github.io/531w20/midterm_project/project15/Midterm_Project.html.
3. W18 Final project, *1928-1931 Detroit Mumps Infection Analysis*. https://ionides.github.io/531w18/final_project/17/final.html.
4. Other W18 Final projects that I found inspiring: *Donation behavior: is the donor alive or dead? Governing the observed number of donors making a donation each month*. https://ionides.github.io/531w18/final_project/43/final.html. *POMP Modeling for Spot-futures Spreads by a Variation of CIR Model*. https://ionides.github.io/531w18/final_project/4/final.html
5. Dataset: *SARS 2003 Outbreak Complete Dataset*. https://www.kaggle.com/imdevskp/sars-outbreak-2003-complete-dataset.